# Generated by Django 5.1.5 on 2025-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_image_newave_image1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newave',
            options={'verbose_name_plural': 'Блоки на главной странице'},
        ),
        migrations.RemoveField(
            model_name='newave',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='newave',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='newave',
            name='image3',
        ),
        migrations.AddField(
            model_name='newave',
            name='block_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание блока'),
        ),
        migrations.AddField(
            model_name='newave',
            name='block_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newave',
            name='images',
            field=models.JSONField(blank=True, null=True, verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='settings',
            name='main_page_heading',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок главной страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='main_page_subheading',
            field=models.CharField(default=1, max_length=255, verbose_name='Подзаголовок главной страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='main_page_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст главной страницы'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tema',
            field=models.CharField(max_length=50, verbose_name='Тема сайта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок сайта'),
        ),
    ]
