# Generated by Django 5.1.5 on 2025-01-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_newave_options_remove_newave_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото проекта')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на проект')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.AlterModelOptions(
            name='newave',
            options={'verbose_name_plural': 'Описание'},
        ),
        migrations.RemoveField(
            model_name='newave',
            name='block_description',
        ),
        migrations.RemoveField(
            model_name='newave',
            name='block_title',
        ),
        migrations.RemoveField(
            model_name='newave',
            name='images',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='main_page_heading',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='main_page_subheading',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='main_page_text',
        ),
        migrations.AddField(
            model_name='newave',
            name='image1',
            field=models.ImageField(default=1, upload_to='newave/', verbose_name='Фото 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newave',
            name='image2',
            field=models.ImageField(default=1, upload_to='newave/', verbose_name='Фото 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newave',
            name='image3',
            field=models.ImageField(default=1, upload_to='newave/', verbose_name='Фото 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='tema',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
