# Generated by Django 5.1.5 on 2025-01-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_delete_client_delete_service_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
