# Generated by Django 5.1.5 on 2025-01-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Изображение проекта')),
                ('categories', models.CharField(help_text='Введите категории через запятую', max_length=255, verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Описание',
            },
        ),
        migrations.AlterModelOptions(
            name='newave',
            options={},
        ),
    ]
