# Generated by Django 5.1.5 on 2025-01-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_portfolio_alter_newave_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
