# Generated by Django 5.1.5 on 2025-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_portfolio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Логотип клиента')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='categories',
            field=models.CharField(help_text='Введите категории через запятую', max_length=155, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Название проекта'),
        ),
    ]
